import Head from 'next/head'
import { Componente } from '../componets/componentedefinitivo'

export default function Home() {
  return (
    <>
      <Head>
        <title>pagina principal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Componente>
        hola asjdhasdhaskljdhasjkl
      </Componente>
    </>
  )
}
