import Head from 'next/head'
import { Aside, Fotter, Header, Nav } from '../componets/linkesheader'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Nav/>
      <Aside>
        <h1>hola esta es la Pagina principal</h1>
      </Aside>
      
      <Fotter/>
    </div>
  )
}
